# Generated by Django 2.1.5 on 2019-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0005_auto_20190412_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='subforum',
            name='subforum_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
