# Generated by Django 2.1.5 on 2019-04-14 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmiforums', '0006_auto_20190414_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date-of-Birth'),
        ),
    ]
